### ISSUE TITLE
new wiki page

### ISSUE THREAD

**Issue by zivoy** [ppotatoo/ssapi#2]
I can't contribute to the wiki directly, so il post it here:
from the ranking requests page https://new.scoresaber.com/ranking/requests
there is
https://new.scoresaber.com/api/ranking/requests/top
and
https://new.scoresaber.com/api/ranking/requests/belowtop
on the page itself, it is calling `belowTop` but I found that the capitalization does not matter when making the request

**Comment by meizuflux** [comment]
Thanks, I have added this to the wiki.
