### ISSUE TITLE
update user profile

### ISSUE THREAD

**Issue by zivoy** [ppotatoo/ssapi#3]
I found another url.
if you call
`https://new.scoresaber.com/api/user/{uid}/refresh`
then it refreshes the user's info (average acc, etc.)

**Comment by zivoy** [comment]
Endpoint was removed.
Don't know if this is temporary. It might do a refresh whenever you call on the user info or on a schedule. But it's no longer on a get request.
The button that called this request was also removed

**Comment by meizuflux** [comment]
👍🏻
